# Generated by Django 5.0.1 on 2024-01-11 00:03

import TaskManager.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название приоритетности')),
            ],
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название статуса')),
            ],
        ),
        migrations.CreateModel(
            name='TGUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.IntegerField(unique=True, verbose_name='TG ID')),
                ('email', models.CharField(max_length=255, verbose_name='email')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Подтверждена учетная запись?')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Заголовок задачи')),
                ('text', models.TextField(verbose_name='Текст задачи')),
                ('deadline_date', models.DateTimeField(verbose_name='Дата дедлайна')),
                ('finished', models.BooleanField(default=False, verbose_name='Завершена?')),
                ('priority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TaskManager.taskpriority', verbose_name='Приоритет')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TaskManager.taskstatus', verbose_name='Статус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskManager.tguser', verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=TaskManager.models.generate_random_code, verbose_name='Код')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskManager.tguser', verbose_name='Пользователь TG')),
            ],
        ),
    ]
