# Generated by Django 5.0.1 on 2024-01-11 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationcode',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TaskManager.tguser', verbose_name='Пользователь TG'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline_date',
            field=models.DateTimeField(null=True, verbose_name='Дата дедлайна'),
        ),
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.TextField(null=True, verbose_name='Текст задачи'),
        ),
    ]
