# Generated by Django 5.0.1 on 2024-01-11 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0002_alter_confirmationcode_user_alter_task_deadline_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TaskManager.tguser', verbose_name='Пользователь'),
        ),
    ]
